### ISSUE TITLE
Error message config

### ISSUE THREAD

**Issue by dontirun** [aws-samples/aws-ai-qna-bot#94] opened 2018-06-01 23:00 UTC
<a href="https://github.com/JohnCalhoun"><img src="https://avatars1.githubusercontent.com/u/13800333?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JohnCalhoun](https://github.com/JohnCalhoun)**
_Monday Apr 16, 2018 at 15:01 GMT_
_Originally opened as https://github.com/rstrahan/aws-ai-qna-bot-2/issues/12_

----

support lex error message config in designer ui/ api

**Comment by JohnCalhoun** [comment] 2018-06-12 20:48
duplicate of #121

**Closed by JohnCalhoun** 2018-06-12 20:48 UTC
