### ISSUE TITLE
Response card fields are not presented in a logical order 

### ISSUE THREAD

**Issue by rstrahan** [aws-samples/aws-ai-qna-bot#89] opened 2018-05-31 19:13 UTC
## Expected Behavior

Response card fields should be presented in a logical order - 
1. Title
2. Subtitle (optional)
3. URL

## Actual Behavior

Subtitle comes first, title comes last.. confusing

![image](https://user-images.githubusercontent.com/10953374/40802908-f90d6b46-64e4-11e8-83d7-092d5847f42f.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:

**Comment by JohnCalhoun** [comment] 2018-06-12 20:50
duplicate of #116

**Closed by JohnCalhoun** 2018-06-12 20:50 UTC
